### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1

### ISSUE THREAD

**Issue by ys144756** [waynejo/android-ndk-gif#1]
when i encode first frame got error.

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf0f65a68 in tid 28019 (Thread-10404)

**Comment by waynejo** [comment]
Can you share original image or some details of original image for me?
It will help to fix.

**Comment by ys144756** [comment]
i just pull master branch and setting up gradle (settings.gralde file and library's gralde file) and run sample code.

did i something wrong?

**Comment by ys144756** [comment]
and please mark license on readme file :)

**Comment by cjztool** [comment]
got this:
... Fatal signal 11 (SIGSEGV), code 2, fault addr 0x417ceccc in tid 25878 (Thread-7179)

**Comment by ys144756** [comment]
and..

when i load file for decode gif image, heap memory was abnormally grow up.

image link : http://66.media.tumblr.com/0d5ed85f652a0dd357d66221a0cb04e7/tumblr_nyxrlsrDsI1s5f7v4o1_1280.gif

**Comment by waynejo** [comment]
Hello!

Sorry, But I want to know something.
Are you korean?

From Wayne.

2016. 6. 1. 오후 7:19 김영수 <notifications@github.com> 작성:

**Comment by ys144756** [comment]
yes. i'm korean.

**Comment by waynejo** [comment]
Oh, Sorry.
I thought It's mail. So, I hoped to send mail to you with korean language.
If you can, please let me know your email address via my email.
My email is waynejo1024@gmail.com .

**Comment by inventionsbyhamid** [comment]
Facing the same issue. Any details how can I resolve this?
