### ISSUE TITLE
Transparent gifs 

### ISSUE THREAD

**Issue by marcinkwiatkowski** [waynejo/android-ndk-gif#17]
Hi! Are transparent gifs not "officially" supported? When I encode bitmaps with transparent pixels, I can see glitches in the resulted gif.

**Comment by waynejo** [comment]
There seems to be a bug when transparent regions overlap.
I'll fix it soon.

**Comment by waynejo** [comment]
I fixed the problem.
Would you like to use version 0.3.3?

**Comment by marcinkwiatkowski** [comment]
Nice one, confirming that the issue is fixed :) Thanks!
