### ISSUE TITLE
android-ndk-gif is slower than none-ndk-gif encoder

### ISSUE THREAD

**Issue by ys144756** [waynejo/android-ndk-gif#2]
i compared two library but ndk-gif was more slower than none-ndk-gif encoder.

is there anything difference?

link : https://gist.github.com/wasabeef/8785346

**Comment by waynejo** [comment]
https://gist.github.com/wasabeef/8785346 makes a lower quality image.

I added ENCODING_TYPE_SIMPLE_FAST option in 0.3.0 version.
If you want fast encoding, please use it.
