### ISSUE TITLE
Please push library to maven central or jitpack since jcenter will shutdown

### ISSUE THREAD

**Issue by truefedex** [waynejo/android-ndk-gif#40]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by StephenGiant** [comment]
seems he does'nt care about this

**Comment by BastyZ** [comment]
@waynejo is there any possibility  that this library can be pushed to another repository handler like MavenCentral ?

**Comment by waynejo** [comment]
Change the storage path as follows.

`
    maven {
        url 'https://repo1.maven.org/maven2'
    }
`

Change the version to 1.0.1 as shown below.

`
implementation ('io.github.waynejo:androidndkgif:1.0.1')
`

thank you.
