### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by amarkovits** [waynejo/android-ndk-gif#5]
When I try to encode a gif I get this error:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ro.markosoft.gifrecorder-1/base.apk"],nativeLibraryDirectories=[/data/app/ro.markosoft.gifrecorder-1/lib/arm64, /data/app/ro.markosoft.gifrecorder-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libandroidndkgif.so"

I'm testing on a Nexus 5x.

This is my build.gradle:

`
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "22.0.1"

```
defaultConfig {
    applicationId "ro.markosoft.gifrecorder"
    minSdkVersion 21
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:21.0.0'
    compile 'com.android.support:recyclerview-v7:21.0.0'
    compile 'com.facebook.fresco:fresco:0.12.0'
    compile('com.waynejo:androidndkgif:0.3.1')
}
`

**Comment by amanvij** [comment]
Hi, 
I am getting same error on Nexus 6P and zenfone2. Please let me know the solution to resolve this.

Thanks,
Aman
